---

- name: Install kubernetes packages
  hosts: ALL_k8s
  become: yes
  tasks:
  - name: Add google GPG repo key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  - name: Add kubernetes repository
    apt_repository:
     repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
     filename: kubernetes
  - name: Add docker repo key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Install docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      filename: docker

  - name: Apt update and install kubernetes
    apt:
      name:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present
      update_cache: yes
#  - name: Hold packages
#    dpkg_selections:
#      name: "{{ item }}"
#      selection: hold
#      with_items:
#      - kubelet
#      - kubeadm
#      - kubectl
#      - kubernetes-cni

- name: Make some setup
  hosts: ALL_k8s
  become: yes
  tasks:
  - name: Disable swap
    shell: swapoff -a
  - name: Edit fstab for swap off
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$' 
      replace: '# \1'
  - name: Enable modules
    modprobe:
      name: "{{ item }}"
      state: present
    with_items:
    - overlay
    - br_netfilter
  - name: Load-module br_netfilter to /etc/sysctl.d/k8s.conf/k8s.conf
    lineinfile:
      path: /etc/modules-load.d/k8s.conf
      regexp: '^br_netfilter'
      line: br_netfilter
      create: yes
  - name: Config iptables bridge in /etc/sysctl.d/k8s.conf
    lineinfile:
      path: /etc/sysctl.d/k8s.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      create: yes
    with_items:
    - { regexp: '^net.bridge.bridge-nf-call-ip6tables', line: 'net.bridge.bridge-nf-call-ip6tables = 1' }
    - { regexp: '^net.bridge.bridge-nf-call-iptables', line: 'net.bridge.bridge-nf-call-iptables = 1' }
  - name: Enable Params
    shell: sysctl --system
  - name: Config Docker cgroupdriver
    copy:
      src: ./files/daemon.json
      dest: /etc/docker/
      mode: u+rw,g-wx,o-wx
    notify:
    - Docker restart




  handlers:
  - name: Docker restart
    systemd:
      name: docker
      state: restarted

